apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: console-prometheus
spec:
  replicas: 1
  serviceAccountName: console-prometheus-server
  podMonitorSelector:
    matchLabels:
      app: console-kafka-monitor
  serviceMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  additionalScrapeConfigs:
    name: kubernetes-scrape-configs
    key: prometheus-additional.yaml
