---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proxy

resources:
- proxy-namespace.yaml
- proxy-deployment.yaml
- proxy-envelope-encryption-vault-token-secret.yaml  # Note: This file is created during the PREPARE_KMS.md step

