upstream:
  git_repo: https://github.com/strimzi/strimzi-kafka-operator.git
  branch: release-0.11.x
  registry: ''
  family: strimzi
  prefix: ''
  suffix: ''
  version: 0.11.4
downstream:
  git_repo: https://github.com/jboss-container-images/amqstreams-1-openshift-image
  branch: amqstreams11-cp
  registry: registry.access.redhat.com
  family: amq7
  prefix: amq-streams
  suffix: ''
  version: 1.1.1
  osbs:
    repository: containers/amqstreams-1
    prefix: rh-amqstreams-1.1
    suffix: openshift-cp-rhel-7
jars:
  kafka-base:
      - name: kafka.tar.gz
        version: kafka-2.0.0
        md5: 5e35768a5b0ccb13bd3f34643f7135aa
      - name: kafka.tar.gz
        version: kafka-2.1.1
        md5: f7ba47e7528800576c3fe7b05c1188b2
      - name: jmx_prometheus_javaagent.jar
        md5: 89e83b40f70c9ca43a409e5b485555bc
  cluster-operator:
      - name: cluster-operator.jar
        md5: 576ad5bd8f5da1f77a00fb269297ad9b
  topic-operator:
      - name: topic-operator.jar
        md5: 6a252b6b748f1541a5ff009253ba8816
  user-operator:
      - name: user-operator.jar
        md5: bddcda41a8d8688c5c6f46de61177aa9
  kafka-init:
      - name: kafka-init.jar
        md5: e6802930edfb3826295b85c2276d9652
  java-base:
      - name: strimzi_licenses.tgz
        md5: c53c36ba9ab2dc6d6b9bb1969780bb75
cluster:
  local:
    user: admin
    password: admin
    namespace: myproject
    url: https://127.0.0.1:8443
    registry: 172.30.1.1:5000
  remote:
    user: unused
    namespace: ""
    url: ""
    registry: ""
images:
  - cluster-operator
  - entity-operator-stunnel
  - java-base
  - kafka-base
  - kafka-connect-s2i
  - kafka-connect
  - kafka-init
  - kafka-mirror-maker
  - kafka-stunnel
  - kafka
  - stunnel-base
  - topic-operator
  - user-operator
  - zookeeper-stunnel
  - zookeeper
