upstream:
  git_repo: https://github.com/strimzi/strimzi-kafka-operator.git
  branch: release-0.11.x
  registry: ''
  family: strimzi
  prefix: ''
  suffix: ''
  tag: 0.11.0
downstream:
  git_repo: https://github.com/jboss-container-images/amqstreams-1-openshift-image
  branch: amqstreams11-dev
  registry: registry.access.redhat.com
  family: amq7
  prefix: amq-streams
  suffix: ''
  tag: 1.1.0
  osbs:
    repository: containers/amqstreams-1
    prefix: rh-amqstreams-1.1
    suffix: openshift-rhel-7
images:
  - cluster-operator
  - entity-operator-stunnel
  - java-base
  - kafka-base
  - kafka-connect-s2i
  - kafka-connect
  - kafka-init
  - kafka-mirror-maker
  - kafka-stunnel
  - kafka
  - stunnel-base
  - topic-operator
  - user-operator
  - zookeeper-stunnel
  - zookeeper
