upstream:
  git_repo: https://github.com/strimzi/strimzi-kafka-operator.git
  branch: release-0.11.x
  registry: ''
  family: strimzi
  prefix: ''
  suffix: ''
  version: 0.11.0
downstream:
  git_repo: https://github.com/jboss-container-images/amqstreams-1-openshift-image
  branch: amqstreams11-dev
  registry: registry.access.redhat.com
  family: amq7
  prefix: amq-streams
  suffix: ''
  version: 1.1.0
  osbs:
    repository: containers/amqstreams-1
    prefix: rh-amqstreams-1.1
    suffix: openshift-rhel-7
jars:
  kafka-base:
      - name: kafka.tar.gz
        version: kafka-2.0.0
        md5: 5e35768a5b0ccb13bd3f34643f7135aa
      - name: kafka.tar.gz
        version: kafka-2.1.1
        md5: f7ba47e7528800576c3fe7b05c1188b2
      - name: jmx_prometheus_javaagent.jar
        md5: 89e83b40f70c9ca43a409e5b485555bc
  cluster-operator:
      - name: cluster-operator.jar
        md5: b5afb903a8d5c585ab4a47de51228100
  topic-operator:
      - name: topic-operator.jar
        md5: 9c380c28cfe2ff9f9952ab92d0b7c949
  user-operator:
      - name: user-operator.jar
        md5: e352a770ac94f1f87b06865250eb03ff
  kafka-init:
      - name: kafka-init.jar
        md5: 64e5c804f24932a378cb7ae1c781d519
  java-base:
      - name: strimzi_licenses.tgz
        md5: 6df7007701c8c4e6a5d87e7a7c8ece1c
cluster:
  local:
    user: admin
    password: admin
    namespace: myproject
    url: https://127.0.0.1:8443
    registry: 172.30.1.1:5000
  remote:
    user: unused
    namespace: ""
    url: ""
    registry: ""
images:
  - cluster-operator
  - entity-operator-stunnel
  - java-base
  - kafka-base
  - kafka-connect-s2i
  - kafka-connect
  - kafka-init
  - kafka-mirror-maker
  - kafka-stunnel
  - kafka
  - stunnel-base
  - topic-operator
  - user-operator
  - zookeeper-stunnel
  - zookeeper
