apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnectS2I
metadata:
  name: my-connect-cluster
spec:
  replicas: 1
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  metrics:
    lowercaseOutputName: true