RELEASE_TAG = "rhaos-middleware-rhel-9-container-released"
OPERATOR_PACKAGE_NAME = "amqstreams-operator-container"
MAVEN_BUILDER_PACKAGE_NAME = "amqstreams-maven-builder-container"
METADATA_PACKAGE_NAME = "amqstreams-bundle-container"
PACKAGE_NAME_SUFFIX = "-container"
RELEASED = False
COMPLETED = 1
OLD_BUNDLE_VERSION_INDEX=0
NEW_BUNDLE_VERSION_INDEX=1
