RELEASE_TAG = "rhaos-middleware-rhel-8-container-released"
OPERATOR_PACKAGE_NAME = "amqstreams-operator-container"
METADATA_PACKAGE_NAME = "amqstreams-bundle-container"
PACKAGE_NAME_SUFFIX = "-container"
STRIMZI_MAVEN_BUILDER = "strimzi-maven-builder"
RELEASED = False
COMPLETED = 1
OLD_BUNDLE_VERSION_INDEX=0
NEW_BUNDLE_VERSION_INDEX=1