---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: consoles.console.streamshub.github.com
spec:
  group: console.streamshub.github.com
  names:
    kind: Console
    plural: consoles
    singular: console
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              env:
                items:
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                    valueFrom:
                      properties:
                        configMapKeyRef:
                          properties:
                            key:
                              type: string
                            name:
                              type: string
                            optional:
                              type: boolean
                          type: object
                        fieldRef:
                          properties:
                            apiVersion:
                              type: string
                            fieldPath:
                              type: string
                          type: object
                        resourceFieldRef:
                          properties:
                            containerName:
                              type: string
                            divisor:
                              anyOf:
                              - type: integer
                              - type: string
                              x-kubernetes-int-or-string: true
                            resource:
                              type: string
                          type: object
                        secretKeyRef:
                          properties:
                            key:
                              type: string
                            name:
                              type: string
                            optional:
                              type: boolean
                          type: object
                      type: object
                  type: object
                type: array
              hostname:
                type: string
              images:
                properties:
                  api:
                    type: string
                  ui:
                    type: string
                type: object
              kafkaClusters:
                items:
                  properties:
                    adminProperties:
                      properties:
                        values:
                          items:
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        valuesFrom:
                          items:
                            properties:
                              configMapRef:
                                properties:
                                  name:
                                    type: string
                                  optional:
                                    type: boolean
                                type: object
                              prefix:
                                type: string
                              secretRef:
                                properties:
                                  name:
                                    type: string
                                  optional:
                                    type: boolean
                                type: object
                            type: object
                            x-kubernetes-validations:
                            - message: One of `configMapRef` or `secretRef` is required
                              rule: has(self.configMapRef) || has(self.secretRef)
                          type: array
                      type: object
                    consumerProperties:
                      properties:
                        values:
                          items:
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        valuesFrom:
                          items:
                            properties:
                              configMapRef:
                                properties:
                                  name:
                                    type: string
                                  optional:
                                    type: boolean
                                type: object
                              prefix:
                                type: string
                              secretRef:
                                properties:
                                  name:
                                    type: string
                                  optional:
                                    type: boolean
                                type: object
                            type: object
                            x-kubernetes-validations:
                            - message: One of `configMapRef` or `secretRef` is required
                              rule: has(self.configMapRef) || has(self.secretRef)
                          type: array
                      type: object
                    credentials:
                      properties:
                        kafkaUser:
                          description: Reference to a Strimzi KafkaUser resource
                          properties:
                            name:
                              type: string
                            namespace:
                              type: string
                          required:
                          - name
                          type: object
                      type: object
                      x-kubernetes-validations:
                      - message: kafkaUser is required
                        rule: has(self.kafkaUser)
                    id:
                      description: |-
                        Identifier to be used for this Kafka cluster in the console. When the console is connected to Kubernetes and a Strimzi Kafka custom resource may be discovered using the name and namespace properties, this property is optional. Otherwise, the Kafka cluster identifier published in the Kafka resource's status will be used. If namespace is not given or the console or Kubernetes is not in use, and this property is not provided, the ID will default to the name.

                        When provided, this property will override the Kafka cluster ID available in the Kafka resource's status.
                      type: string
                    listener:
                      description: The name of the listener in the Strimzi Kafka Kubernetes
                        resource that should be used by the console to establish connections.
                      type: string
                    name:
                      description: "The name of the Kafka cluster. When the console\
                        \ is connected to Kubernetes, a Strimzi Kafka custom resource\
                        \ may be discovered using this property together with the\
                        \ namespace property. In any case, this property will be displayed\
                        \ in the console for the Kafka cluster's name."
                      type: string
                    namespace:
                      description: "The namespace of the Kafka cluster. When the console\
                        \ is connected to Kubernetes, a Strimzi Kafka custom resource\
                        \ may be discovered using this property together with the\
                        \ name property."
                      type: string
                    producerProperties:
                      properties:
                        values:
                          items:
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        valuesFrom:
                          items:
                            properties:
                              configMapRef:
                                properties:
                                  name:
                                    type: string
                                  optional:
                                    type: boolean
                                type: object
                              prefix:
                                type: string
                              secretRef:
                                properties:
                                  name:
                                    type: string
                                  optional:
                                    type: boolean
                                type: object
                            type: object
                            x-kubernetes-validations:
                            - message: One of `configMapRef` or `secretRef` is required
                              rule: has(self.configMapRef) || has(self.secretRef)
                          type: array
                      type: object
                    properties:
                      properties:
                        values:
                          items:
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        valuesFrom:
                          items:
                            properties:
                              configMapRef:
                                properties:
                                  name:
                                    type: string
                                  optional:
                                    type: boolean
                                type: object
                              prefix:
                                type: string
                              secretRef:
                                properties:
                                  name:
                                    type: string
                                  optional:
                                    type: boolean
                                type: object
                            type: object
                            x-kubernetes-validations:
                            - message: One of `configMapRef` or `secretRef` is required
                              rule: has(self.configMapRef) || has(self.secretRef)
                          type: array
                      type: object
                  required:
                  - name
                  type: object
                  x-kubernetes-validations:
                  - message: Property `listener` may not be used when `namespace`
                      is omitted
                    rule: '!has(self.listener) || has(self.__namespace__)'
                type: array
            required:
            - hostname
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: "Last time the condition of a type changed from\
                        \ one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ',\
                        \ in the UTC time zone"
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        the condition's last transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition
                        (a single word in CamelCase).
                      type: string
                    status:
                      description: "The status of the condition, either True, False\
                        \ or Unknown."
                      type: string
                    type:
                      description: "The unique identifier of a condition, used to\
                        \ distinguish between other conditions in the resource."
                      type: string
                  type: object
                type: array
              observedGeneration:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
