---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consolereconciler-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: consolereconciler-cluster-role
subjects:
  - kind: ServiceAccount
    name: console-operator
    namespace: "${NAMESPACE}"
