---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: console-operator
  name: console-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: console-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: console-operator
    spec:
      serviceAccountName: console-operator
      containers:
        - name: console-operator
          image: registry.redhat.io/amq-streams/console-operator-rhel9:2.8
          imagePullPolicy: Always
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONSOLE_DEPLOYMENT_DEFAULT_API_IMAGE
              value: registry.redhat.io/amq-streams/console-api-rhel9:2.8
            - name: CONSOLE_DEPLOYMENT_DEFAULT_UI_IMAGE
              value: registry.redhat.io/amq-streams/console-ui-rhel9:2.8
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
