apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  version: 3.5.0
  replicas: 1
  consumer:
    bootstrapServers: cluster-a-kafka-bootstrap:9092 # Source cluster
    groupId: cluster-a-group-id
  producer:
    bootstrapServers: cluster-b-kafka-bootstrap:9092 # Target cluster
  include: ".*"
