apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  version: 3.5.0
  replicas: 1
  consumer:
    bootstrapServers: cluster-a-kafka-bootstrap:9093 # Source cluster
    groupId: cluster-a-group-id
    tls:
      trustedCertificates:
        - secretName: cluster-a-cluster-ca-cert
          certificate: ca.crt
  producer:
    bootstrapServers: cluster-b-kafka-bootstrap:9093 # Target cluster
    tls:
      trustedCertificates:
        - secretName: cluster-b-cluster-ca-cert
          certificate: ca.crt
  include: ".*"
