apiVersion: v1
kind: Template
metadata:
  name: amqstreams-1-clusteroperator
  annotations:
    openshift.io/display-name: "AMQ Streams (Cluster Operator)"
    description: >-
      Application template for AMQ Streams. It installs the Cluster Operator.
    tags: "messaging,amq"
    iconClass: "fa fa-share-alt fa-flip-horizontal"
message: "The Cluster Operator is being deployed."
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: strimzi-cluster-operator
    labels:
      app: strimzi
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: Role
  metadata:
    name: strimzi-cluster-operator-role
    labels:
      app: strimzi
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - watch
    - delete
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - "extensions"
    resources:
    - deployments
    - deployments/scale
    - replicasets
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - "apps"
    resources:
    - deployments
    - deployments/scale
    - deployments/status
    - statefulsets
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
  # OpenShift S2I requirements
  - apiGroups:
    - "extensions"
    resources:
    - replicationcontrollers
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - apps.openshift.io
    resources:
    - deploymentconfigs
    - deploymentconfigs/scale
    - deploymentconfigs/status
    - deploymentconfigs/finalizers
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - build.openshift.io
    resources:
    - buildconfigs
    - builds
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - watch
    - update
  - apiGroups:
    - image.openshift.io
    resources:
    - imagestreams
    - imagestreams/status
    verbs:
    - create
    - delete
    - get
    - list
    - watch
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - replicationcontrollers
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    name: strimzi-cluster-operator-binding
    labels:
      app: strimzi
  subjects:
    - kind: ServiceAccount
      name: strimzi-cluster-operator
  roleRef:
    kind: Role
    name: strimzi-cluster-operator-role
    apiGroup: rbac.authorization.k8s.io
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: strimzi-cluster-operator
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: strimzi-cluster-operator
      spec:
        serviceAccountName: strimzi-cluster-operator
        containers:
          - name: strimzi-cluster-operator
            image: redhat-amqstreams-1/amqstreams10-clustercontroller-openshift:1.0
            env:
              - name: STRIMZI_CONFIGMAP_LABELS
                value: ${STRIMZI_CONFIGMAP_LABELS}
              - name: STRIMZI_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
                value: ${STRIMZI_FULL_RECONCILIATION_INTERVAL_MS}
              - name: STRIMZI_OPERATION_TIMEOUT_MS
                value: ${STRIMZI_OPERATION_TIMEOUT_MS}
              - name: STRIMZI_DEFAULT_ZOOKEEPER_IMAGE
                value: redhat-amqstreams-1/amqstreams10-zookeeper-openshift:1.0
              - name: STRIMZI_DEFAULT_KAFKA_IMAGE
                value: redhat-amqstreams-1/amqstreams10-kafka-openshift:1.0
              - name: STRIMZI_DEFAULT_KAFKA_CONNECT_IMAGE
                value: redhat-amqstreams-1/amqstreams10-kafkaconnect-openshift:1.0
              - name: STRIMZI_DEFAULT_KAFKA_CONNECT_S2I_IMAGE
                value: redhat-amqstreams-1/amqstreams10-kafkaconnects2i-openshift:1.0
              - name: STRIMZI_DEFAULT_TOPIC_CONTROLLER_IMAGE
                value: redhat-amqstreams-1/amqstreams10-topiccontroller-openshift:1.0
            livenessProbe:
              httpGet:
                path: /healthy
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 30
            readinessProbe:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 30
    strategy:
      type: Recreate
parameters:
- description: The OpenShift label selector used to identify ConfigMaps to be managed by the operator.
  displayName: CLuster configuration label selector
  name: STRIMZI_CONFIGMAP_LABELS
  value: "strimzi.io/kind=cluster"
- description: The interval between periodic reconciliations, in milliseconds.
  displayName: Reconciliation interval
  name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
  value: 120000
- description: The timeout for internal operations, in milliseconds.
  displayName: Internal operations timeout
  name: STRIMZI_OPERATION_TIMEOUT_MS
  value: 60000
