#!/bin/bash
set -e
set -x

for arg in "$@"
do
  if [[ "$arg" = -D* ]]; 
  then
    JAVA_OPTS="${JAVA_OPTS} ${arg}"
  else
    APP_OPTS="${APP_OPTS} ${arg}"
  fi
done

# Disable FIPS if needed
if [ "$FIPS_MODE" = "disabled" ]; then
    JAVA_OPTS="${JAVA_OPTS} -Dcom.redhat.fips=false"
fi

exec java $JAVA_OPTS -jar /drain-cleaner.jar $APP_OPTS
