---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: console-operator
spec:
  name: amq-streams-console
  channel: alpha
  source: redhat-operators
  sourceNamespace: openshift-marketplace
