---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  config.yaml: |
    adminHttp:
      port: 9190
      endpoints:
        prometheus: {}
    virtualClusters:
      my-cluster-proxy:
        # the virtual cluster is kafka proxy that sits between kafka clients and the real kafka cluster.  clients
        # connect to the virtual cluster rather than real cluster.
        clusterNetworkAddressConfigProvider:
          # this is the networking scheme used to present the virtual cluster on the network
          type: PortPerBrokerClusterNetworkAddressConfigProvider
          config:
            # this is the address the clients will refer to in their bootstrap.servers configuration.
            bootstrapAddress: localhost:9092
            brokerAddressPattern: aad5a82ca85ec48419a72d2a6d1b3d12-9280ad3d8feae0f1.elb.us-east-1.amazonaws.com
            brokerStartPort: 19092
            numberOfBrokerPorts: 3
        targetCluster:
          # declares the kafka cluster that is being proxied
          bootstrap_servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        logFrames: false
    filters:
    - type: RecordEncryption
      config:
        # User: uncomment this section if you are using AWS.
        # Change region identifier in the region and endpointUrl if you are using a region other than us-east-1.
        #kms: AwsKmsService
        #kmsConfig:
        #  endpointUrl: https://kms.us-east-1.amazonaws.com
        #  region: us-east-1
        #  accessKey:
        #    passwordFile: /opt/proxy/encryption/kms-secrets/accessKeyId.txt
        #  secretKey:
        #    passwordFile: /opt/proxy/encryption/kms-secrets/secretAccessKey.txt
        # User: uncomment this section if you are using Vault.
        #kms: VaultKmsService
        #kmsConfig:
        #  vaultTransitEngineUrl: http://vault.vault.svc.cluster.local:8200/v1/transit
        #  vaultToken:
        #    passwordFile: /opt/proxy/encryption/kms-secrets/token.txt
        selector: TemplateKekSelector
        selectorConfig:
          template: "KEK_${topicName}"
