---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  config.yaml: |
    virtualClusters:
      my-cluster-proxy:
        # the virtual cluster is kafka proxy that sits between kafka clients and the real kafka cluster.  clients
        # connect to the virtual cluster rather than real cluster.
        clusterNetworkAddressConfigProvider:
          # this is the networking scheme used to present the virtual cluster on the network
          type: PortPerBrokerClusterNetworkAddressConfigProvider
          config:
            # this is the address the clients will refer to in their bootstrap.servers configuration.
            bootstrapAddress: localhost:9092
            brokerAddressPattern: a5babde172a1c417dbd4fd7ecc64625f-c70f3d074bf71d17.elb.us-east-1.amazonaws.com
            brokerStartPort: 19092
            numberOfBrokerPorts: 3
        targetCluster:
          # declares the kafka cluster that is being proxied
          bootstrap_servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        logFrames: false
    filters:
    - type: EnvelopeEncryption
      config:
        kms: VaultKmsService
        kmsConfig:
          vaultTransitEngineUrl: http://vault.vault.svc.cluster.local:8200/v1/transit
          vaultToken:
            passwordFile: /opt/proxy/envelope-encryption/token.txt
        selector: TemplateKekSelector
        selectorConfig:
          template: "KEK_${topicName}"
