apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker2
metadata:
  name: my-mm2-cluster
  labels:
    app: my-mm2-cluster
spec:
  version: 2.4.0
  replicas: 1
  connectCluster: my-cluster
  clusters:
    - alias: my-cluster
      bootstrapServers: my-cluster-kafka-bootstrap:9092
  metrics:
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
    - pattern : "kafka.connect<type=connect-worker-metrics>([^:]+):"
      name: "kafka_connect_connect_worker_metrics_$1"
    - pattern : "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
      name: "kafka_connect_connect_metrics_$1_$2"
